salus:
  environment: local
  kafka-listener-auto-start: true
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ${spring.application.name}-${salus.environment}
      auto-offset-reset: latest
      properties:
        spring.deserializer.value.delegate.class: com.rackspace.monplat.protocol.UniversalMetricFrameDeserializer
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        generate_statistics: false
    show-sql: false
  datasource:
    username: dev
    password: pass
    url: jdbc:mysql://localhost:3306/default?verifyServerCertificate=false&useSSL=false&requireSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
management:
  metrics:
    export:
      influx:
        uri: ${salus.metrics.influx.uri:http://localhost:8086}
        db: salus
        enabled: ${salus.metrics.influx.enabled:false}