server:
  port: 8092
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        generate_statistics: false
    show-sql: false
  datasource:
    username: dev
    password: pass
    url: jdbc:mysql://localhost:3306/default?verifyServerCertificate=false&useSSL=false&requireSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  kafka:
    listener:
      # this will allow for us to start consumer of a particular topic before the producer
      missing-topics-fatal: false
logging:
  level:
    com.rackspace.salus: debug
    web: debug
management:
  endpoints:
    web:
      exposure:
        # enable further access to endpoints like /actuator/caches and /actuator/metrics
        include: "*"