salus:
  environment: local
spring:
  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ${spring.application.name}-${salus.environment}
      auto-offset-reset: latest
      properties:
        spring.deserializer.value.delegate.class: com.rackspace.monplat.protocol.ExternalMetricDeserializer
management:
  metrics:
    export:
      influx:
        uri: ${salus.metrics.influx.uri:http://localhost:8086}
        db: salus
        enabled: ${salus.metrics.influx.enabled:false}